# Generated by Django 3.2.14 on 2022-07-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20220731_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
