# Generated by Django 3.2.14 on 2022-08-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tour_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
    ]
