# Generated by Django 3.2.14 on 2022-08-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_remove_tour_book_tour_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_duration',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_name',
            field=models.CharField(max_length=250),
        ),
    ]
