# Generated by Django 3.2.14 on 2022-08-26 17:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_auto_20220826_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartureTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.CharField(choices=[('9:00', '9am'), ('11:00', '11am'), ('13:00', '1pm'), ('15:00', '3pm'), ('20:00', '8pm')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_tour_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('departure_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.departuretime')),
                ('tour_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tour')),
            ],
            options={
                'ordering': ['-book_tour_date'],
            },
        ),
    ]
