# Generated by Django 3.2.14 on 2022-08-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_auto_20220826_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(help_text='Note Any Specific Requirements Here', max_length=500, null=True),
        ),
    ]
