# Generated by Django 3.2.14 on 2022-08-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_booking_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, help_text='Note Any Specific Requirements Here', max_length=500, null=True),
        ),
    ]
