# Generated by Django 3.2.14 on 2022-09-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
