# Generated by Django 3.2.14 on 2022-09-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_tour_departure_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='departure_times',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
