# Generated by Django 3.2.14 on 2022-09-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_alter_tour_departure_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='departure_times',
            new_name='has_departure_times',
        ),
    ]
