# Generated by Django 3.2.14 on 2022-09-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_rename_departure_times_tour_has_departure_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='has_departure_times',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
