# Generated by Django 3.2.14 on 2022-09-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0020_alter_tour_has_departure_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='has_departure_date',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
