# Generated by Django 3.2.14 on 2022-09-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0021_tour_has_departure_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='has_departure_times',
        ),
        migrations.AddField(
            model_name='tour',
            name='departure_time',
            field=models.CharField(blank=True, choices=[('9:00', '9am'), ('11:00', '11am'), ('13:00', '1pm'), ('15:00', '3pm'), ('20:00', '8pm')], max_length=5),
        ),
    ]
