# Generated by Django 3.2.14 on 2022-09-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0022_auto_20220907_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='departure_time',
            field=models.CharField(blank=True, choices=[('9am', '9am'), ('11am', '11am'), ('1pm', '1pm'), ('3pm', '3pm'), ('8pm', '8pm')], max_length=5),
        ),
    ]
