# Generated by Django 3.2.14 on 2022-09-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0024_alter_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='departure_date',
            field=models.DateField(null=True),
        ),
    ]
