# Generated by Django 3.2.14 on 2022-09-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0026_remove_tour_has_departure_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='departure_time',
            new_name='has_departure_time',
        ),
    ]
