# Generated by Django 3.2.14 on 2022-09-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0027_rename_departure_time_tour_has_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
