# Generated by Django 3.2.14 on 2022-09-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0029_auto_20220925_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='departure_date',
        ),
    ]
