# Generated by Django 3.2.14 on 2022-09-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_orderlineitem_depart_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='tour_departure_date',
        ),
    ]
