# Generated by Django 3.2.14 on 2022-10-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
