# Generated by Django 3.2.14 on 2022-08-29 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0015_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_tour_date', models.DateField()),
                ('departure_time', models.CharField(choices=[('9:00', '9am'), ('11:00', '11am'), ('13:00', '1pm'), ('15:00', '3pm'), ('20:00', '8pm')], max_length=5)),
                ('quantity', models.PositiveSmallIntegerField(help_text='Number of TimeHoppers over 18 years old only')),
                ('notes', models.TextField(blank=True, help_text='Note Any Specific Requirements Here', max_length=500, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('tour_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tour')),
            ],
            options={
                'ordering': ['-book_tour_date'],
            },
        ),
    ]
