# Generated by Django 3.2.14 on 2022-08-30 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_auto_20220830_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='tour_name',
            new_name='tour',
        ),
    ]
