# Generated by Django 3.2.14 on 2022-09-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_auto_20220902_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
