# Generated by Django 3.2.14 on 2022-09-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_auto_20220902_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='booking_items',
            field=models.ManyToManyField(related_name='booking_items', to='basket.Booking'),
        ),
    ]
