# Generated by Django 3.2.14 on 2022-09-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_alter_basket_booking_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
