# Generated by Django 3.2.14 on 2022-09-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_alter_booking_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='quantity',
            field=models.PositiveSmallIntegerField(help_text='Number of TimeHoppers over 18 years old only'),
        ),
    ]
