# Generated by Django 3.2.14 on 2022-09-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_alter_booking_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookingitem',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingItem',
        ),
    ]
